install:
    # install latest release version of hugo
    - curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | grep -E '"browser_download_url":[[:space:]]*".*hugo_[0-9]+\.[0-9]+_Linux-64bit.tar.gz"' | cut -d ':' -f 2- | xargs wget
    - tar -xzf hugo* 

script:
    - ./hugo

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  email: $GITHUB_EMAIL
  name: $GITHUB_USERNAME
  keep-history: true
  local_dir: public
  repo: uncleshushu.github.io
  target-branch: master
  on:
    branch: master